export const VALIDATION_REGEX = {
    PASSWORD: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&.])[A-Za-z\d@$!%*?&.]{8,}$/,
    EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    ONLY_LETTERS: /^[A-Za-zÁÉÍÓÚÑáéíóúñ]+$/,
    ONLY_LETTERS_AND_SPACES: /^[A-Za-zÁÉÍÓÚÑáéíóúñ ]+$/,
    ONLY_NUMBERS: /^\d+$/,
    ALPHANUMERIC: /^[A-Za-zÁÉÍÓÚÑáéíóúñ0-9]+$/,
    PHONE_MX: /^\d{10}$/,
    RFC_MX: /^([A-ZÑ&]{3,4})(\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])([A-Z\d]{2})([A\d])$/,
    CLABE: /^\d{18}$/,
    TIME_HHMM: /^([01]\d|2[0-3]):([0-5]\d)$/,
    DECIMAL_2: /^\d+(?:[.,]\d{1,2})?$/,
};

export const VALIDATION_MESSAGES = {
    REQUIRED: "Campo obligatorio",
    EMAIL_INVALID: "Correo electrónico inválido",
    EMAIL_DOMAIN: "Solo correos @utez.edu.mx, @cona.com o @gmail.com permitidos",
    PASSWORD_MIN_LENGTH: "La contraseña debe tener al menos 8 caracteres",
    PASSWORD_UPPERCASE: "La contraseña debe incluir al menos una mayúscula",
    PASSWORD_LOWERCASE: "La contraseña debe incluir al menos una minúscula",
    PASSWORD_DIGIT: "La contraseña debe incluir al menos un dígito",
    PASSWORD_SPECIAL: "La contraseña debe incluir al menos un carácter especial (@$!%*?&.)",
    PASSWORD_CONFIRM_MISMATCH: "Las contraseñas no coinciden",
    ONLY_LETTERS: "Solo letras",
    ONLY_LETTERS_AND_SPACES: "Solo letras y espacios",
    ONLY_NUMBERS: "Solo números",
    ALPHANUMERIC: "Solo letras y números",
    MIN_LENGTH: (min) => `Mínimo ${min} caracteres`,
    MAX_LENGTH: (max) => `Máximo ${max} caracteres`,
    MIN_DIGITS: (min) => `Mínimo ${min} dígitos`,
    MAX_DIGITS: (max) => `Máximo ${max} dígitos`,
    POSITIVE_NUMBER: "Debe ser un número positivo",
    PHONE_INVALID: "Teléfono inválido (10 dígitos)",
    RFC_INVALID: "RFC inválido",
    CLABE_INVALID: "CLABE inválida (18 dígitos)",
    TIME_INVALID: "Formato HH:mm inválido",
    INTEGER_RANGE: (min, max) => `Valor fuera de rango (${min}-${max})`,
    DECIMAL_INVALID: "Monto inválido",
    TEXT_GENERAL_INVALID: "Caracteres no permitidos",
    STARTS_WITH_UPPER: "Debe iniciar con mayúscula",
    DATE_INVALID: "Fecha inválida",
    DATE_AFTER: (date) => `Debe ser después de ${date}`,
    DATE_BEFORE: (date) => `Debe ser antes de ${date}`,
    DATE_BETWEEN: (start, end) => `Debe estar entre ${start} y ${end}`,
};
